services:
  pg:
    container_name: brevly-db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly

    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./docker:/docker-entrypoint-initdb.d"

  migratedb:
    container_name: migratedb
    build:
      context: .
      target: dependencies
    depends_on:
      - pg
    environment:
      - DATABASE_URL=
    command: sh /entrypoint.sh
    working_dir: /usr/src/app

  app:
    container_name: brevly-server
    build:
      context: .
    ports:
      - 3333:3333
    depends_on:
      - pg
      - migratedb
    environment:
      - DATABASE_URL=
      - CLOUDFARE_ACCOUNT_ID=
      - CLOUDFARE_ACCESS_KEY_ID=
      - CLOUDFARE_SECRET_ACCESS_KEY=
      - CLOUDFARE_BUCKET=
      - CLOUDFARE_PUBLIC_URL=

volumes:
  pgdata:
